"""Compatibility shim: stem artifact validation moved to apps.stems.artifacts.

This code moved to apps.stems.artifacts on Mon 14 Sep 2026 to satisfy the
.importlinter "webui-is-the-top-layer" contract. New code must import
apps.stems.artifacts directly rather than this shim.
"""

from apps.stems.artifacts import (
    DEFAULT_STEMS_DIR,
    FRAME_MISMATCH_TOL_S,
    LOGGER,
    ROFORMER_PARTS,
    ROFORMER_STEMS_DIR,
    STEM_LAYOUTS,
    STEM_PARTS,
    STEM_SUMMARY_TTL_S,
    DemucsModel,
    StemArtifactError,
    StemBundle,
    StemBundleNotFoundError,
    StemManifest,
    StemPart,
    StemSourceProvenance,
    WavMetadata,
    bulk_stem_summaries,
    load_stem_bundle,
    read_flac_metadata,
    read_mp3_metadata,
    read_stem_container_metadata,
    read_wav_metadata,
    scan_mp3_frames,
    stem_roots,
    stems_accept_v2,
    summarize_stem_bundle,
    validate_stable_id,
)

__all__ = [
    "DEFAULT_STEMS_DIR",
    "FRAME_MISMATCH_TOL_S",
    "LOGGER",
    "ROFORMER_PARTS",
    "ROFORMER_STEMS_DIR",
    "STEM_LAYOUTS",
    "STEM_PARTS",
    "STEM_SUMMARY_TTL_S",
    "DemucsModel",
    "StemArtifactError",
    "StemBundle",
    "StemBundleNotFoundError",
    "StemManifest",
    "StemPart",
    "StemSourceProvenance",
    "WavMetadata",
    "bulk_stem_summaries",
    "load_stem_bundle",
    "read_flac_metadata",
    "read_mp3_metadata",
    "read_stem_container_metadata",
    "read_wav_metadata",
    "scan_mp3_frames",
    "stem_roots",
    "stems_accept_v2",
    "summarize_stem_bundle",
    "validate_stable_id",
]
