/** Query token -> extra catalog tokens for keyword search. */
export const SETTINGS_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
	dark: ['theme', 'appearance', 'light'],
	light: ['theme', 'appearance', 'dark'],
	night: ['theme', 'dark'],
	day: ['theme', 'light'],
	missing: ['hide_broken_links', 'broken', 'file'],
	broken: ['hide_broken_links', 'missing'],
	density: ['library_density', 'compact', 'cosy'],
	cozy: ['cosy', 'library_density'],
	cosy: ['library_density', 'compact'],
	compact: ['library_density'],
	preview: ['preview_beat_sync', 'cue'],
	sync: ['beat_sync_max', 'auto_sync', 'rekordbox', 'djay', 'auto_play_enabled'],
	beatsync: ['beat_sync_max', 'preview_beat_sync', 'sync'],
	autoplay: ['auto_play_enabled', 'next'],
	phase: ['beat_sync_max', 'bar'],
	next: ['next_only_filter', 'camelot'],
	compatible: ['next_only_filter', 'camelot'],
	camelot: ['next_only_filter', 'key'],
	remix: ['remixes_filter', 'bootleg', 'vip'],
	vocals: ['vocals_filter', 'lyrics', 'lines'],
	karaoke: ['lyrics_global', 'lyrics_waveform_overlay', 'lyrics_deck_line'],
	lyrics: ['lyrics_global', 'lyrics_library_col', 'lyrics_hover_scrub', 'lyrics_load_strategy'],
	confirm: ['confirm.delete_playlist', 'confirm.dblclick_load_play', 'confirm.playlist_drop_mode'],
	prompt: ['confirm'],
	writeback: ['auto_sync', 'ratings', 'rekordbox', 'djay'],
	ratings: ['auto_sync', 'writeback'],
	rekordbox: ['auto_sync', 'rb'],
	djay: ['auto_sync'],
	opendj: ['open_dj', 'auto_sync'],
	'open-dj': ['open_dj', 'auto_sync'],
	todo: ['hide_todo_settings', 'parity'],
	gray: ['hide_todo_settings', 'todo'],
	grey: ['hide_todo_settings', 'todo'],
	placeholder: ['hide_todo_settings', 'todo']
};
