/** Query token -> extra catalog tokens for keyword search. */
export const SETTINGS_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
	dark: ['theme', 'appearance', 'light'],
	light: ['theme', 'appearance', 'dark'],
	night: ['theme', 'dark'],
	day: ['theme', 'light'],
	missing: ['hide_broken_links', 'broken', 'file'],
	broken: ['hide_broken_links', 'missing'],
	density: ['library_density', 'compact', 'cosy'],
	cozy: ['cosy', 'library_density'],
	cosy: ['library_density', 'compact'],
	compact: ['library_density'],
	sync: ['beat_sync_max', 'auto_sync', 'rekordbox', 'djay', 'auto_play_enabled'],
	beatsync: ['beat_sync_max', 'sync'],
	autoplay: ['auto_play_enabled', 'next'],
	phase: ['beat_sync_max', 'bar'],
	next: ['next_only_filter', 'camelot'],
	camelot: ['next_only_filter', 'key'],
	confirm: ['confirm.delete_playlist', 'confirm.dblclick_load_play'],
	prompt: ['confirm'],
	writeback: ['auto_sync', 'ratings', 'rekordbox', 'djay'],
	ratings: ['auto_sync', 'writeback'],
	rekordbox: ['auto_sync', 'rb'],
	djay: ['auto_sync'],
	opendj: ['open_dj', 'auto_sync'],
	'open-dj': ['open_dj', 'auto_sync'],
	todo: ['hide_todo_settings', 'parity'],
	gray: ['hide_todo_settings', 'todo'],
	grey: ['hide_todo_settings', 'todo'],
	placeholder: ['hide_todo_settings', 'todo']
};
