"""Render and check the live security-system status block in docs/security/security.md.

Requirement SEC-02 (Mon 14 Sep 2026): the security docs show EXACTLY what the
security review system does today. Every row is derived from files in the
repo, so the doc cannot claim a check that is not wired, and
tests/test_security_status_doc.py fails the build when doc and repo drift.

A second marker pins the SWOT to the table it was written against: when the
table changes, the SWOT must be re-read and re-acknowledged (--ack-swot).

Usage:
    python -m scripts.security.security_status --check     # exit 1 when stale
    python -m scripts.security.security_status --write     # regenerate the table
    python -m scripts.security.security_status --ack-swot  # after re-reading the SWOT

Requirements (mini-PRD):
  ✔︎ ✅ 🎯 Derive every row from repo files, never from a hand-kept list of states.
    [if a workflow gains osv-scanner and the row still says NOT WIRED then broken]
  ✔︎ ✅ 🎯 Fail --check when the doc block differs from the rendered block.
    [if the doc claims WIRED for a check no workflow runs then broken]
  ✔︎ ✅ 🎯 Fail --check when the SWOT marker does not match the current table hash.
    [if the table changes and the SWOT is not re-acknowledged then broken]
  ✔︎ ✅ 🎯 Zero of zero is not a pass.
    [if an empty repo reports any check as WIRED then broken]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import tomllib
from dataclasses import dataclass
from functools import cached_property
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
DOC_REL = "docs/security/security.md"
BLOCK_BEGIN = (
    "<!-- security-status:begin (generated by scripts/security/security_status.py; do not edit) -->"
)
BLOCK_END = "<!-- security-status:end -->"
SWOT_MARKER_RE = re.compile(r"<!-- swot-reviewed-for: ([0-9a-f]{12}|UNSET) -->")

WIRED = "WIRED"
NOT_WIRED = "NOT WIRED"
EXTERNAL = "EXTERNAL"
# ADR-0043: security reports, it does not block merges, until the promotion gate exists.
MERGE_BLOCKING = "no"

OSV_CHECK = "Dependency vulnerability scan (osv-scanner)"
GENERAL_REVIEW_CHECK = "General AI code review"


# ----- repo facts -------------------------------------------------------------
@dataclass(frozen=True)
class RepoFacts:
    root: Path

    def text(self, rel: str) -> str:
        path = self.root / rel
        return path.read_text(encoding="utf-8") if path.is_file() else ""

    @cached_property
    def workflows(self) -> dict[str, str]:
        wf_dir = self.root / ".github" / "workflows"
        if not wf_dir.is_dir():
            return {}
        return {p.name: p.read_text(encoding="utf-8") for p in sorted(wf_dir.glob("*.y*ml"))}

    @cached_property
    def ci_text(self) -> str:
        """Workflow YAML plus every repo script those workflows invoke."""
        workflow_text = "\n".join(self.workflows.values())
        invoked = sorted(set(re.findall(r"scripts/[\w./-]+\.(?:sh|py)", workflow_text)))
        return "\n".join([workflow_text, *(self.text(rel) for rel in invoked)])

    @cached_property
    def pyproject(self) -> dict[str, Any]:
        raw = self.text("pyproject.toml")
        return tomllib.loads(raw) if raw else {}

    def tool_config(self, *keys: str) -> Any:
        node: Any = self.pyproject.get("tool", {})
        for key in keys:
            node = node.get(key, {}) if isinstance(node, dict) else {}
        return node


@dataclass(frozen=True)
class Row:
    check: str
    where: str
    state: str
    evidence: str
    blocks_merge: str = MERGE_BLOCKING


# ----- detectors: scanners -----------------------------------------------------
def _ci_tool_row(facts: RepoFacts, check: str, where: str, needle: str) -> Row:
    found = needle in facts.ci_text
    evidence = (
        f"`{needle}` invoked from .github/workflows" if found else f"no workflow invokes `{needle}`"
    )
    return Row(check, where, WIRED if found else NOT_WIRED, evidence)


def _precommit_gitleaks_row(facts: RepoFacts) -> Row:
    found = "gitleaks" in facts.text(".pre-commit-config.yaml")
    evidence = (
        "hook in .pre-commit-config.yaml"
        if found
        else "no gitleaks hook in .pre-commit-config.yaml"
    )
    return Row(
        "Secret scan, staged changes (gitleaks)",
        "pre-commit (local; skippable)",
        WIRED if found else NOT_WIRED,
        evidence,
        "local only",
    )


def _zizmor_row(facts: RepoFacts) -> Row:
    in_ci = "zizmor" in facts.ci_text
    in_hook = "zizmor" in facts.text(".pre-commit-config.yaml")
    places = [name for name, on in (("workflows", in_ci), ("pre-commit", in_hook)) if on]
    evidence = f"runs in {' + '.join(places)}" if places else "not in workflows or pre-commit"
    return Row(
        "GitHub Actions audit (zizmor)", "PR + pre-commit", WIRED if places else NOT_WIRED, evidence
    )


def _ruff_s_row(facts: RepoFacts) -> Row:
    select = (
        facts.tool_config("ruff", "lint").get("select", [])
        if isinstance(facts.tool_config("ruff", "lint"), dict)
        else []
    )
    on = "S" in select
    evidence = (
        '`"S"` in [tool.ruff.lint] select' if on else '`"S"` absent from [tool.ruff.lint] select'
    )
    return Row(
        "Python security lint (ruff S)",
        "pre-commit + quality ratchet",
        WIRED if on else NOT_WIRED,
        evidence,
    )


# ----- detectors: supply chain and fixes -----------------------------------------
def _workflow_permissions_row(facts: RepoFacts) -> Row:
    workflows = facts.workflows
    missing = [
        name for name, body in workflows.items() if not re.search(r"^permissions:", body, re.M)
    ]
    state = WIRED if workflows and not missing else NOT_WIRED
    declared = len(workflows) - len(missing)
    evidence = f"{declared} of {len(workflows)} workflows declare top-level permissions"
    if missing:
        evidence += f"; missing: {', '.join(missing)}"
    return Row("Least-privilege workflow tokens", "every workflow", state, evidence)


def _renovate_row(facts: RepoFacts) -> Row:
    found = [
        rel for rel in ("renovate.json", ".github/renovate.json") if (facts.root / rel).is_file()
    ]
    evidence = (
        f"{found[0]} on this tree" if found else "no renovate.json (onboarding PR not merged)"
    )
    return Row(
        "Dependency fix PRs (Renovate)", "Mend-hosted app", WIRED if found else NOT_WIRED, evidence
    )


def _uv_cooldown_row(facts: RepoFacts) -> Row:
    value = (
        facts.tool_config("uv").get("exclude-newer")
        if isinstance(facts.tool_config("uv"), dict)
        else None
    )
    evidence = f"[tool.uv] exclude-newer = {value!r}" if value else "no [tool.uv] exclude-newer"
    return Row(
        "Release-age cooldown, PyPI (uv)", "install time", WIRED if value else NOT_WIRED, evidence
    )


def _pnpm_cooldown_row(facts: RepoFacts) -> Row:
    workspaces = sorted(
        [
            *facts.root.glob("apps/*/pnpm-workspace.yaml"),
            *facts.root.glob("apps/*/*/pnpm-workspace.yaml"),
        ]
    )
    explicit = [
        p
        for p in workspaces
        if re.search(r"^minimumReleaseAge:\s*\d+", p.read_text(encoding="utf-8"), re.M)
    ]
    state = WIRED if workspaces and len(explicit) == len(workspaces) else NOT_WIRED
    evidence = f"explicit minimumReleaseAge in {len(explicit)} of {len(workspaces)} pnpm workspaces"
    return Row("Release-age cooldown, npm (pnpm)", "install time", state, evidence)


def _lockfile_install_row(facts: RepoFacts) -> Row:
    requirement_install = re.compile(r"pip install\b.*\s-r\s+\S*requirements[\w.-]*\.txt")
    locked_install = re.compile(r"uv sync\b.*--(?:frozen|locked)|pnpm install\b.*--frozen-lockfile")
    offenders = [name for name, body in facts.workflows.items() if requirement_install.search(body)]
    locked = [name for name, body in facts.workflows.items() if locked_install.search(body)]
    state = WIRED if locked and not offenders else NOT_WIRED
    if offenders:
        evidence = f"installs from floating requirements*.txt in: {', '.join(offenders)}"
    elif locked:
        evidence = f"locked installs in {len(locked)} workflows, none from requirements*.txt"
    else:
        evidence = (
            "no locked install (`uv sync --frozen`, `pnpm install --frozen-lockfile`)"
            " in any workflow"
        )
    return Row("CI installs only locked versions", "CI", state, evidence)


# ----- detectors: review, app hardening, release ------------------------------------
def _general_review_row(facts: RepoFacts) -> Row:
    match = re.search(
        r"EXPECTED_REVIEWERS[^=]*=\s*\(([^)]*)\)", facts.text("scripts/review_coverage.py")
    )
    if not match:
        return Row(
            GENERAL_REVIEW_CHECK,
            "every PR",
            NOT_WIRED,
            "no EXPECTED_REVIEWERS in scripts/review_coverage.py",
        )
    names = [token.strip().strip("'\"") for token in match.group(1).split(",") if token.strip()]
    mentions = len(re.findall(r"\bsecurity\b", facts.text("scripts/review_prompt.py"), re.I))
    evidence = (
        f"reviewers: {', '.join(names)}; `security` appears {mentions}x"
        " in scripts/review_prompt.py (no security checklist)"
    )
    return Row(GENERAL_REVIEW_CHECK, "every PR (coverage-gated)", WIRED, evidence)


def _weekly_ai_review_row(facts: RepoFacts) -> Row:
    rel = "ops/security/weekly-security-review.md"
    check, where = "Weekly AI security review", "scheduled Claude routine"
    prompt = facts.text(rel)
    schedule = re.search(r"^Schedule: (.+)$", prompt, re.M)
    if not prompt:
        return Row(check, where, NOT_WIRED, f"no {rel}")
    if not schedule:
        return Row(
            check, where, NOT_WIRED, f"prompt in {rel} but no `Schedule:` line: routine not created"
        )
    return Row(
        check, where, EXTERNAL, f"prompt in {rel}; routine outside the repo: {schedule.group(1)}"
    )


def _daemon_guard_row(facts: RepoFacts) -> Row:
    wiring = facts.text("apps/webui/server/app_wiring.py") + facts.text("apps/webui/server/app.py")
    on = (facts.root / "apps/webui/server/request_guard.py").is_file() and "request_guard" in wiring
    evidence = (
        "request_guard.py mounted by the webui app (SEC-01)" if on else "no request_guard mounted"
    )
    return Row(
        "Daemon Host/Origin guard", "runtime (app)", WIRED if on else NOT_WIRED, evidence, "n/a"
    )


def _tauri_csp_row(facts: RepoFacts) -> Row:
    raw = facts.text("apps/desktop/src-tauri/tauri.conf.json")
    csp = json.loads(raw).get("app", {}).get("security", {}).get("csp") if raw else None
    evidence = (
        "app.security.csp set in tauri.conf.json"
        if csp
        else "no app.security.csp in tauri.conf.json"
    )
    return Row(
        "Webview Content-Security-Policy",
        "runtime (app)",
        WIRED if csp else NOT_WIRED,
        evidence,
        "n/a",
    )


def _release_verify_row(facts: RepoFacts) -> Row:
    shell_scripts = (
        sorted((facts.root / "scripts").glob("*.sh")) if (facts.root / "scripts").is_dir() else []
    )
    verifying = [
        p.name for p in shell_scripts if "codesign --verify" in p.read_text(encoding="utf-8")
    ]
    evidence = (
        f"`codesign --verify` in {', '.join(verifying)} (run by hand, not CI)"
        if verifying
        else "no `codesign --verify` step"
    )
    return Row(
        "Release signature verification",
        "per DMG release (local)",
        WIRED if verifying else NOT_WIRED,
        evidence,
        "n/a",
    )


def _promotion_gate_row(facts: RepoFacts) -> Row:
    gates = [name for name in facts.workflows if "promot" in name]
    evidence = (
        f"workflow: {', '.join(gates)}"
        if gates
        else "design only: docs/security/merge-and-promotion.md"
    )
    return Row(
        "Promotion gate, private -> public repo",
        "promotion",
        WIRED if gates else NOT_WIRED,
        evidence,
        "yes, once wired",
    )


def _external_rows() -> list[Row]:
    """GitHub settings the repo tree cannot show. Re-verify with the commands named."""
    return [
        Row(
            "Dependabot alerts",
            "GitHub setting",
            EXTERNAL,
            "enabled Mon 14 Sep 2026; verify:"
            " `gh api repos/<repo>/vulnerability-alerts` returns 204",
        ),
        Row(
            "Renovate GitHub App",
            "GitHub setting",
            EXTERNAL,
            "installed Mon 14 Sep 2026 on this repo only; verify: Settings > Applications",
        ),
    ]


def collect_rows(facts: RepoFacts) -> list[Row]:
    return [
        _ci_tool_row(facts, OSV_CHECK, "PR + daily", "osv-scanner"),
        _ci_tool_row(facts, "Secret scan, PR commits (gitleaks)", "PR", "gitleaks"),
        _precommit_gitleaks_row(facts),
        _ci_tool_row(facts, "Verified secrets, full history (trufflehog)", "weekly", "trufflehog"),
        _ci_tool_row(facts, "Static analysis (Semgrep CE)", "PR", "semgrep"),
        _ci_tool_row(
            facts, "Static analysis (Semgrep AppSec Platform)", "PR + weekly", "semgrep ci"
        ),
        _ruff_s_row(facts),
        _zizmor_row(facts),
        _workflow_permissions_row(facts),
        _general_review_row(facts),
        _weekly_ai_review_row(facts),
        _renovate_row(facts),
        _uv_cooldown_row(facts),
        _pnpm_cooldown_row(facts),
        _lockfile_install_row(facts),
        _daemon_guard_row(facts),
        _tauri_csp_row(facts),
        _release_verify_row(facts),
        _promotion_gate_row(facts),
        *_external_rows(),
    ]


# ----- render and check ------------------------------------------------------------
def render_block(rows: list[Row]) -> str:
    wired = sum(row.state == WIRED for row in rows)
    lines = [
        BLOCK_BEGIN,
        f"**{wired} of {len(rows)} checks wired in this tree."
        " Security blocks no merges (ADR-0043).**",
        "",
        "| Check | Where it runs | State | Blocks merge | Evidence |",
        "|---|---|---|---|---|",
        *(f"| {r.check} | {r.where} | {r.state} | {r.blocks_merge} | {r.evidence} |" for r in rows),
        BLOCK_END,
    ]
    return "\n".join(lines)


def block_hash(block: str) -> str:
    return hashlib.sha256(block.encode("utf-8")).hexdigest()[:12]


def _current_block(doc: str) -> str:
    start, end = doc.find(BLOCK_BEGIN), doc.find(BLOCK_END)
    if start < 0 or end < start:
        raise ValueError(f"{DOC_REL} is missing the security-status markers")
    return doc[start : end + len(BLOCK_END)]


def check_doc(root: Path) -> list[str]:
    doc = (root / DOC_REL).read_text(encoding="utf-8")
    expected = render_block(collect_rows(RepoFacts(root)))
    problems = []
    if _current_block(doc) != expected:
        problems.append(
            "status table is stale: run `python -m scripts.security.security_status --write`"
        )
    marker = SWOT_MARKER_RE.search(doc)
    if not marker:
        problems.append("SWOT marker `<!-- swot-reviewed-for: ... -->` is missing")
    elif marker.group(1) != block_hash(expected):
        problems.append(
            "SWOT was written for a different table: re-read it, update it, then run `--ack-swot`"
        )
    return problems


def write_doc(root: Path, *, ack_swot: bool) -> None:
    path = root / DOC_REL
    doc = path.read_text(encoding="utf-8")
    block = render_block(collect_rows(RepoFacts(root)))
    doc = doc.replace(_current_block(doc), block)
    if ack_swot:
        doc = SWOT_MARKER_RE.sub(f"<!-- swot-reviewed-for: {block_hash(block)} -->", doc)
    path.write_text(doc, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--ack-swot", action="store_true")
    args = parser.parse_args(argv)
    if args.check:
        problems = check_doc(REPO_ROOT)
        for problem in problems:
            print(f"[ERROR] {problem}", file=sys.stderr)
        if not problems:
            print(f"[OK] {DOC_REL} matches the repo")
        return 1 if problems else 0
    write_doc(REPO_ROOT, ack_swot=args.ack_swot)
    print(f"[OK] wrote {DOC_REL}" + (" and acknowledged the SWOT" if args.ack_swot else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
