"""Reversal-log writer for USB apply.

Every mutating run opens a ``reversal-<ts>.sh`` file, writes a header,
and appends one line per executed op so an operator can undo the run
with ``bash reversal-<ts>.sh``.

Reversal semantics (matches Phase 1):

* ``copy`` / ``transcode`` -- ``rm -v "<dst>"``
* ``overwrite`` with backup -- ``rm -v "<dst>" && mv -v "<backup>" "<dst>"``
* ``overwrite`` without backup -- ``rm -v "<dst>"`` (can't restore content)
* ``delete`` -- ``echo "cannot restore deleted file <path>"`` (we warn)
* ``rename`` -- ``mv -v "<new>" "<old>"``

The script is written with ``set -euo pipefail`` + ``chmod +x``. We
provide ``bash -n`` syntax validation via ``verify_syntax``.
"""
from __future__ import annotations

import datetime as _dt
import os
import shlex
import subprocess
from dataclasses import dataclass
from pathlib import Path

from apps.sync.usb.copy import CopyResult


def ts_slug() -> str:
    return _dt.datetime.now().strftime("%Y-%m-%d-%H%M")


@dataclass(slots=True)
class ReversalLog:
    path: Path
    _lines: list[str]

    @classmethod
    def open(
        cls,
        *,
        dir_: Path,
        profile_name: str,
        mode: str,
        reason: str,
        drive_uuid: str | None,
        tag: str = "apply",
    ) -> "ReversalLog":
        dir_.mkdir(parents=True, exist_ok=True)
        path = dir_ / f"reversal-{ts_slug()}.sh"
        lines = [
            "#!/usr/bin/env bash",
            "# Generated by apps.sync.usb.apply. Safe to `bash` to undo.",
            "#",
            f"# tag:        {tag}",
            f"# profile:    {profile_name}",
            f"# mode:       {mode}",
            f"# reason:     {reason or '(unspecified)'}",
            f"# drive_uuid: {drive_uuid or '(none)'}",
            f"# created:    {_dt.datetime.now().isoformat(timespec='seconds')}",
            "set -euo pipefail",
            "",
        ]
        return cls(path=path, _lines=lines)

    def append(self, result: CopyResult) -> None:
        op = result.op
        if not result.ok:
            self._lines.append(f"# FAILED op {op.kind} {op.dst_rel}: {result.error}")
            return
        if op.kind in ("copy", "transcode"):
            self._lines.append(f'rm -v -- {shlex.quote(str(op.dst))}')
        elif op.kind == "overwrite":
            if result.backup_path is not None:
                self._lines.append(f'rm -v -- {shlex.quote(str(op.dst))}')
                self._lines.append(
                    f'mv -v -- {shlex.quote(str(result.backup_path))} '
                    f'{shlex.quote(str(op.dst))}'
                )
            else:
                self._lines.append(
                    f"# cannot fully restore overwrite of "
                    f"{shlex.quote(str(op.dst))} (no backup kept)"
                )
                self._lines.append(f'rm -v -- {shlex.quote(str(op.dst))}')
        elif op.kind == "delete":
            self._lines.append(
                f"# WARN: cannot restore deleted {shlex.quote(str(op.dst))}"
            )
        elif op.kind == "rename":
            # result.op has new dst; backup_path holds the original location
            # we renamed FROM when we used rename_one.
            if result.backup_path is not None:
                self._lines.append(
                    f'mv -v -- {shlex.quote(str(op.dst))} '
                    f'{shlex.quote(str(result.backup_path))}'
                )
        # skip -> no reversal line needed

    def close(self, summary: str = "") -> None:
        if summary:
            self._lines.append("")
            self._lines.append(f"# {summary}")
        self._lines.append("")
        self.path.write_text("\n".join(self._lines) + "\n", encoding="utf-8")
        os.chmod(self.path, 0o755)


def verify_syntax(path: Path) -> tuple[bool, str]:
    """Run ``bash -n`` on ``path``. Returns (ok, stderr)."""
    try:
        proc = subprocess.run(
            ["bash", "-n", str(path)],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
    except FileNotFoundError:
        return False, "bash not available"
    except subprocess.TimeoutExpired:
        return False, "timeout"
    return proc.returncode == 0, proc.stderr.strip()


__all__ = ["ReversalLog", "ts_slug", "verify_syntax"]
