allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@storybook/addon-docs@10.5.10"
  - "@storybook/builder-vite@10.5.10"
  - "@storybook/csf-plugin@10.5.10"
  - "@storybook/react-dom-shim@10.5.10"
  - "@storybook/svelte-vite@10.5.10"
  - "@storybook/svelte@10.5.10"
  - "@storybook/sveltekit@10.5.10"
  - storybook@10.5.10
patchedDependencies:
  signalsmith-stretch@1.3.2: patches/signalsmith-stretch@1.3.2.patch
