"""Generate specs/parity-checklist.md from reqs.json (v1 scope).

Rebuild lane agentB: the generated file is the parity-MVP acceptance list for
the toolchain surface. Performance-mode UI parity is tracked separately in
PARITY-TODO.md (Working now / Partial / TODO tables) and gates T2/T4.

Run: uv run --no-sync python scripts/build_parity_checklist.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQS = ROOT / "reqs.json"
OUT = ROOT / "specs" / "parity-checklist.md"

_SHIPPED = {"shipped", "done", "complete"}


def main() -> None:
    data = json.loads(REQS.read_text())
    v1 = data["v1"]
    lines = [
        "# Parity checklist - agentB rebuild lane",
        "",
        "GENERATED by scripts/build_parity_checklist.py from reqs.json (v1 scope);",
        "do not edit by hand. Regenerate after any REQUIREMENTS.md sweep.",
        "",
        "Rule: the rebuild reaches parity MVP when every requirement checked below",
        "(shipped in v1) is reproduced on the new chassis AND PARITY-TODO.md's",
        "Working-now table is fully green on it. Unchecked rows were not shipped in",
        "v1 and are NOT parity obligations. Contract changes follow the protocol in",
        ".planning/rebuild-clean-room-take-fable.md s15 T0.",
        "",
    ]
    total = shipped = 0
    for key in sorted(v1):
        cat = v1[key]
        reqs = cat.get("requirements", [])
        if not reqs:
            continue
        lines.append(f"## {cat.get('name', key)}")
        lines.append("")
        for it in reqs:
            rid = it.get("id", "?")
            desc = str(it.get("desc", "")).strip()
            status = str(it.get("status", "?"))
            phase = it.get("shipped_phase") or it.get("phase") or "?"
            mark = "x" if status.lower() in _SHIPPED else " "
            total += 1
            shipped += mark == "x"
            lines.append(f"- [{mark}] **{rid}** {desc} ({status}, {phase})")
        lines.append("")
    lines.append(
        f"Denominator: {total} v1 requirements total; {shipped} shipped in v1 at"
    )
    lines.append(
        "freeze time (the parity obligation set). Re-run this script rather than"
    )
    lines.append("citing remembered figures.")
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"[OK] wrote {OUT.relative_to(ROOT)} ({shipped}/{total} shipped in v1)")


if __name__ == "__main__":
    main()
