"""Dependency license gate: every locked package declares a license, and the license is allowed.

Three files under licenses/ are the contract:

- ``policy.json`` (hand-written): which lockfiles are scanned, the allow and
  deny regexes, the reasoned ``exceptions`` and the reasoned ``overrides``
  (a license fixed by hand where registry metadata is missing or wrong).
- ``register.json`` (generated by ``update``, reviewed in the diff): one line
  per locked ``name@version`` per ecosystem with its license expression.
- ``models.json`` (hand-written): model weights and their code and weights
  licenses, because no lockfile names them.

``check`` is the CI gate. It reads lockfiles and the three JSON files only:
stdlib, no network, no environment, no package code, so it is safe on a
persistent self-hosted runner and takes about a second.

    python -m scripts.license_gate check
    python -m scripts.license_gate update            # fetch licenses for new name@version (network)
    python -m scripts.license_gate update --refresh  # re-fetch every entry

Why name@version and not name: rbox went from MIT/Apache to GPL-3.0-only at
0.1.6, a patch-level bump nobody re-read. Keying on the version makes every
bump re-read the license, which is the only way that change gets caught.

Requirements (mini-PRD)
- [if] a scanned lockfile locks a package whose name@version is not in the
  register [then] ``check`` exits 1 naming it and the update command, [else stop]
- [if] a declared license expression does not evaluate to allowed (OR: any
  branch allowed; AND: every term allowed; deny beats allow; an id matching
  neither is unknown) and no exception names that ecosystem, name and exact
  license [then] ``check`` exits 1, [else stop]
- [if] an exception, override or register entry no longer matches anything
  locked [then] ``check`` exits 1 as stale, so the files cannot rot, [else stop]
- [if] an exception or override has no reason [then] ``check`` exits 1, [else stop]
- [if] a lockfile tracked by git matches a lockfile pattern but is not listed
  in policy.json [then] ``check`` exits 1, so a new lockfile is never skipped
  silently, [else stop]
- [if] a weights file referenced by the payload builders is not declared in
  models.json [then] ``check`` exits 1, [else stop]
- [if] a listed lockfile is missing, does not parse, or yields zero packages
  [then] ``check`` exits 2 (could not measure), never 0, [else stop]
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LICENSES_DIR = Path("licenses")
POLICY = LICENSES_DIR / "policy.json"
REGISTER = LICENSES_DIR / "register.json"
MODELS = LICENSES_DIR / "models.json"

EXIT_OK = 0
EXIT_FINDINGS = 1
EXIT_UNKNOWN = 2

ECOSYSTEMS = ("pypi", "npm", "cargo")
UNKNOWN_LICENSE = "UNKNOWN"

# Tracked files that are lockfiles. A match not listed in policy.json fails
# the gate, so adding a lockfile without scanning it is impossible.
LOCKFILE_PATTERNS = (
    re.compile(r"(^|/)uv\.lock$"),
    re.compile(r"\.py\.lock$"),
    re.compile(r"(^|/)pylock(\.[^/]+)?\.toml$"),
    re.compile(r"(^|/)pnpm-lock\.yaml$"),
    re.compile(r"(^|/)package-lock\.json$"),
    re.compile(r"(^|/)Cargo\.lock$"),
)

# Weights files the payload builders ship. Every basename found here must be
# declared in models.json.
MODEL_SOURCES = ("scripts/build_engine_payload.py", "scripts/payload_*.py")
MODEL_FILE = re.compile(r"[A-Za-z0-9_.-]+\.(?:ckpt|onnx|safetensors|tflite|pt|h5|gguf)\b")


class GateError(Exception):
    """The gate could not measure (exit 2)."""


@dataclass(frozen=True)
class Locked:
    ecosystem: str
    name: str
    version: str
    lockfile: str

    @property
    def key(self) -> str:
        return f"{self.name}@{self.version}"


# ----- lockfile readers (stdlib only) -----------------------------------------


def _read_uv_lock(path: Path) -> Iterator[tuple[str, str]]:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    for pkg in data.get("package", []):
        source = pkg.get("source", {})
        if "editable" in source or "virtual" in source or "directory" in source or "path" in source:
            continue  # the project itself or a local path, not a third-party dependency
        yield pkg["name"], str(pkg.get("version", ""))


def _read_pylock(path: Path) -> Iterator[tuple[str, str]]:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    for pkg in data.get("packages", []):
        if "directory" in pkg:
            continue
        yield pkg["name"], str(pkg.get("version", ""))


def _read_cargo_lock(path: Path) -> Iterator[tuple[str, str]]:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    for pkg in data.get("package", []):
        if "source" not in pkg:
            continue  # a workspace or path crate: our own code
        yield pkg["name"], pkg["version"]


_PNPM_KEY = re.compile(r"^  '?(?P<name>@?[^@\s'(]+)@(?P<version>[^\s'(]+)(?:\([^']*\))?'?:\s*$")


def _read_pnpm_lock(path: Path) -> Iterator[tuple[str, str]]:
    in_packages = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        if not line.startswith(" "):
            in_packages = line.rstrip() == "packages:"
            continue
        if in_packages and (m := _PNPM_KEY.match(line)):
            version = m.group("version")
            if version.startswith(("link:", "file:")):
                continue
            yield m.group("name"), version


def _read_npm_lock(path: Path) -> Iterator[tuple[str, str]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    for key, pkg in data.get("packages", {}).items():
        if not key or pkg.get("link") or "node_modules/" not in key:
            continue
        yield pkg.get("name") or key.rsplit("node_modules/", 1)[1], str(pkg.get("version", ""))


READERS = {
    "uv": ("pypi", _read_uv_lock),
    "pylock": ("pypi", _read_pylock),
    "cargo": ("cargo", _read_cargo_lock),
    "pnpm": ("npm", _read_pnpm_lock),
    "npm": ("npm", _read_npm_lock),
}


def read_lockfile(root: Path, entry: dict) -> list[Locked]:
    rel = entry["path"]
    path = root / rel
    if not path.is_file():
        raise GateError(f"{rel}: listed in {POLICY} but missing")
    ecosystem, reader = READERS[entry["format"]]
    try:
        found = sorted({(_norm_name(ecosystem, n), v) for n, v in reader(path)})
    except (tomllib.TOMLDecodeError, json.JSONDecodeError, KeyError) as exc:
        raise GateError(f"{rel}: does not parse ({exc})") from exc
    if not found:
        raise GateError(f"{rel}: parsed zero packages; the reader or the file is wrong")
    return [Locked(ecosystem, n, v, rel) for n, v in found]


def _norm_name(ecosystem: str, name: str) -> str:
    if ecosystem == "pypi":
        return re.sub(r"[-_.]+", "-", name).lower()
    return name


# ----- license expressions ----------------------------------------------------


# Operators need surrounding whitespace, so the "-or-later" inside an id is
# never read as OR.
_TOKEN = re.compile(r"(\(|\)|\s+(?:AND|OR|and|or)\s+)")


def _tokens(expr: str) -> list[str]:
    return [
        t.strip().upper() if t.strip().upper() in ("AND", "OR") else t.strip()
        for t in _TOKEN.split(expr)
        if t and t.strip()
    ]


_Result = tuple[str, list[str]]


def _combine(op: str, parts: list[_Result]) -> _Result:
    verdicts = [v for v, _ in parts]
    if op == "OR" and "allowed" in verdicts:
        return "allowed", []
    if op == "AND" and all(v == "allowed" for v in verdicts):
        return "allowed", []
    # A failed OR is unknown if any branch could still be cleared by an exception
    # review; a failed AND is denied if any term is denied.
    worse = "unknown" if op == "OR" else "denied"
    better = "denied" if op == "OR" else "unknown"
    verdict = worse if worse in verdicts else better
    return verdict, [o for _, offs in parts for o in offs]


class _Expr:
    """Recursive descent over SPDX tokens: or := and (OR and)*; and := term (AND term)*."""

    def __init__(self, expr: str, allow: list[re.Pattern], deny: list[re.Pattern]) -> None:
        self.expr, self.allow, self.deny = expr, allow, deny
        self.tokens = _tokens(expr)
        self.pos = 0

    def _peek(self) -> str | None:
        return self.tokens[self.pos] if self.pos < len(self.tokens) else None

    def _atom(self, term: str) -> _Result:
        base = re.split(r"\s+WITH\s+", term, flags=re.IGNORECASE)[0].strip()
        if any(p.search(base) for p in self.deny):
            return "denied", [term]
        if any(p.fullmatch(base) for p in self.allow):
            return "allowed", []
        return "unknown", [term]

    def _sequence(self, op: str, operand: Callable[[], _Result]) -> _Result:
        parts = [operand()]
        while self._peek() == op:
            self.pos += 1
            parts.append(operand())
        return parts[0] if len(parts) == 1 else _combine(op, parts)

    def parse_or(self) -> _Result:
        return self._sequence("OR", self.parse_and)

    def parse_and(self) -> _Result:
        return self._sequence("AND", self._term)

    def _term(self) -> _Result:
        tok = self._peek()
        if tok is None:
            return "unknown", [self.expr]
        self.pos += 1
        if tok != "(":
            return self._atom(tok)
        result = self.parse_or()
        if self._peek() == ")":
            self.pos += 1
        return result


def evaluate(expr: str, allow: list[re.Pattern], deny: list[re.Pattern]) -> _Result:
    """Return (verdict, offending ids). verdict is 'allowed', 'denied' or 'unknown'."""
    parser = _Expr(expr, allow, deny)
    if not parser.tokens:
        return "unknown", [expr or "(empty)"]
    result = parser.parse_or()
    if parser.pos != len(parser.tokens):
        return "unknown", [expr]
    return result


# ----- policy and register ----------------------------------------------------


def load_json(root: Path, rel: Path) -> dict:
    path = root / rel
    if not path.is_file():
        raise GateError(f"{rel}: missing")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise GateError(f"{rel}: does not parse ({exc})") from exc


def compile_patterns(policy: dict) -> tuple[list[re.Pattern], list[re.Pattern]]:
    allow = [re.compile(p, re.IGNORECASE) for p in policy["allow"]]
    deny = [re.compile(p, re.IGNORECASE) for p in policy["deny"]]
    if not allow or not deny:
        raise GateError(f"{POLICY}: allow and deny must both be non-empty")
    return allow, deny


def locked_packages(root: Path, policy: dict) -> list[Locked]:
    out: list[Locked] = []
    for entry in policy["lockfiles"]:
        out.extend(read_lockfile(root, entry))
    return out


def tracked_lockfiles(root: Path) -> list[str]:
    try:
        listing = subprocess.run(["git", "ls-files", "-z"], cwd=root, capture_output=True, text=True, check=True).stdout
    except (OSError, subprocess.CalledProcessError) as exc:
        raise GateError(f"git ls-files failed: {exc}") from exc
    files = [f for f in listing.split("\0") if f]
    if not files:
        raise GateError("git ls-files listed nothing; not a checkout?")
    return sorted(f for f in files if any(p.search(f) for p in LOCKFILE_PATTERNS))


def payload_model_files(root: Path) -> set[str]:
    names: set[str] = set()
    sources = [p for pattern in MODEL_SOURCES for p in sorted(root.glob(pattern))]
    if not sources:
        raise GateError(f"none of {MODEL_SOURCES} exist; the model scan is pointed at nothing")
    for source in sources:
        names.update(MODEL_FILE.findall(source.read_text(encoding="utf-8")))
    return names


def _exception_matches(e: dict, ecosystem: str, name: str, license_expr: str) -> bool:
    names = e.get("names") or [e.get("name")]
    licenses = e.get("licenses") or [e.get("license")]
    return e.get("ecosystem") == ecosystem and name in names and license_expr in licenses


def _label(e: dict) -> str:
    names = e.get("names") or [e.get("name")]
    licenses = e.get("licenses") or [e.get("license")]
    return f"{e.get('ecosystem')}/{','.join(map(str, names))} {licenses}"


def _override_key(o: dict) -> tuple[str, str, str | None]:
    return o["ecosystem"], o["name"], o.get("version")


def effective_license(register: dict, overrides: list[dict], pkg: Locked) -> str | None:
    for o in overrides:
        eco, name, version = _override_key(o)
        if eco == pkg.ecosystem and name == pkg.name and version in (None, pkg.version):
            return o["license"]
    return register.get(pkg.ecosystem, {}).get(pkg.key)


# ----- check ------------------------------------------------------------------


class _Check:
    """One pass of the gate. Each method appends findings; nothing here touches the network."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.policy = load_json(root, POLICY)
        self.register = load_json(root, REGISTER)
        self.models = load_json(root, MODELS)
        self.allow, self.deny = compile_patterns(self.policy)
        self.exceptions: list[dict] = self.policy.get("exceptions", [])
        self.overrides: list[dict] = self.policy.get("overrides", [])
        self.lines: list[str] = []
        self.findings: list[str] = []
        self.used_exceptions: set[int] = set()
        self.used_overrides: set[int] = set()
        self.sources: dict[tuple[str, str], list[str]] = {}
        self.unique: dict[tuple[str, str], Locked] = {}

    def lockfile_coverage(self) -> None:
        listed = {e["path"] for e in self.policy["lockfiles"]}
        self.findings.extend(
            f"UNLISTED lockfile {rel}: add it to {POLICY} 'lockfiles'"
            for rel in tracked_lockfiles(self.root)
            if rel not in listed
        )

    def reasons(self) -> None:
        self.findings.extend(
            f"NO REASON for {_label(item)} in {POLICY}"
            for item in self.exceptions + self.overrides
            if not str(item.get("reason", "")).strip()
        )

    def _excepted(self, ecosystem: str, name: str, license_expr: str) -> bool:
        match = [i for i, e in enumerate(self.exceptions) if _exception_matches(e, ecosystem, name, license_expr)]
        self.used_exceptions.update(match)
        return bool(match)

    def packages(self) -> None:
        by_file: dict[str, int] = {}
        for pkg in locked_packages(self.root, self.policy):
            by_file[pkg.lockfile] = by_file.get(pkg.lockfile, 0) + 1
            self.unique.setdefault((pkg.ecosystem, pkg.key), pkg)
            self.sources.setdefault((pkg.ecosystem, pkg.key), []).append(pkg.lockfile)
        self.lines.extend(f"[scan] {rel}: {count} packages" for rel, count in sorted(by_file.items()))
        for (eco, key), pkg in sorted(self.unique.items()):
            self.used_overrides.update(
                i
                for i, o in enumerate(self.overrides)
                if _override_key(o)[:2] == (eco, pkg.name) and _override_key(o)[2] in (None, pkg.version)
            )
            self._package(eco, key, pkg)

    def _package(self, eco: str, key: str, pkg: Locked) -> None:
        where = ", ".join(self.sources[(eco, key)])
        license_expr = effective_license(self.register, self.overrides, pkg)
        if license_expr is None:
            self.findings.append(
                f"UNDECLARED {eco} {key} (in {where}): run "
                "`python -m scripts.license_gate update` and commit licenses/register.json"
            )
            return
        verdict, offending = evaluate(license_expr, self.allow, self.deny)
        if verdict == "allowed" or self._excepted(eco, pkg.name, license_expr):
            return
        self.findings.append(
            f"{verdict.upper()} {eco} {key} license {license_expr!r} (offending: {', '.join(offending)}) "
            f"in {where}: drop or replace the dependency, or add a reasoned entry to {POLICY} 'exceptions'"
        )

    def model_weights(self) -> None:
        declared_files: set[str] = set()
        models = self.models.get("models", [])
        for model in models:
            declared_files.update(model.get("files", []))
            for field in ("code_license", "weights_license"):
                expr = model[field]
                verdict, _ = evaluate(expr, self.allow, self.deny)
                if verdict == "allowed" or self._excepted("model", model["id"], expr):
                    continue
                self.findings.append(
                    f"{verdict.upper()} model {model['id']} {field} {expr!r}: add a reasoned "
                    f"exception (ecosystem 'model') to {POLICY} or stop using it"
                )
        self.findings.extend(
            f"UNDECLARED model file {name} in a payload builder: declare it in {MODELS}"
            for name in sorted(payload_model_files(self.root) - declared_files)
        )
        self.lines.append(f"[scan] {MODELS}: {len(models)} models")

    def stale(self) -> None:
        self.findings.extend(
            f"STALE exception {_label(e)}: nothing locked or declared matches it any more; "
            "remove it (or a name/license in it)"
            for i, e in enumerate(self.exceptions)
            if i not in self.used_exceptions
        )
        self.findings.extend(
            f"STALE override {o['ecosystem']}/{o['name']}: nothing locked matches it; remove it"
            for i, o in enumerate(self.overrides)
            if i not in self.used_overrides
        )
        for eco in ECOSYSTEMS:
            locked_keys = {k for (e, k) in self.unique if e == eco}
            self.findings.extend(
                f"STALE register entry {eco} {key}: run `python -m scripts.license_gate update`"
                for key in sorted(set(self.register.get(eco, {})) - locked_keys)
            )


def run_check(root: Path) -> tuple[int, list[str]]:
    check = _Check(root)
    check.lockfile_coverage()
    check.reasons()
    check.packages()
    check.model_weights()
    check.stale()
    check.lines.append(
        f"[scan] {len(check.unique)} unique name@version across {len(check.policy['lockfiles'])} lockfiles; "
        f"{len(check.used_exceptions)} exceptions in use"
    )
    return (EXIT_FINDINGS if check.findings else EXIT_OK), check.lines + check.findings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("check", help="offline gate (CI)")
    upd = sub.add_parser("update", help="fetch licenses for new name@version entries (network)")
    upd.add_argument("--refresh", action="store_true", help="re-fetch every entry")
    args = parser.parse_args(argv)
    try:
        if args.command == "update":
            from scripts.license_gate_update import run_update  # network half, kept out of the CI import

            return run_update(args.repo_root, args.refresh)
        code, lines = run_check(args.repo_root)
    except GateError as exc:
        print(f"[UNKNOWN] {exc}", file=sys.stderr)
        return EXIT_UNKNOWN
    for line in lines:
        print(line if line.startswith("[") else f"[FAIL] {line}")
    print(
        "[OK] every locked dependency declares an allowed or excepted license"
        if code == EXIT_OK
        else f"[FAIL] {sum(1 for x in lines if not x.startswith('['))} license finding(s)"
    )
    return code


if __name__ == "__main__":
    sys.exit(main())
