"""Pytest plugin — builds ``coverage-matrix.md`` from ``@pytest.mark.requirement``.

Loaded from ``conftest.py`` at repo root via ``pytest_plugins``. The plugin:

  * Adds ``--no-coverage-matrix`` to suppress output.
  * Collects every ``@pytest.mark.requirement("<ID>")`` marker during
    collection (both module-level and parametrize-level are honored).
  * On session finish, writes ``coverage-matrix.md`` with one row per
    requirement: IDs are sourced from ``reqs.json`` so orphan markers
    (ID not in reqs.json) get flagged with ❌.
  * Also flags requirements with zero covering tests (⚠️).

No coverage data is read here — this is purely **traceability**, not line
coverage. Line coverage runs separately via ``pytest --cov``.
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

REPO_ROOT: Path = Path(__file__).resolve().parents[1]
REQS_JSON: Path = REPO_ROOT / "reqs.json"
OUTPUT: Path = REPO_ROOT / "coverage-matrix.md"


def pytest_addoption(parser) -> None:  # type: ignore[no-untyped-def]
    parser.addoption(
        "--no-coverage-matrix",
        action="store_true",
        default=False,
        help="Skip writing coverage-matrix.md after the session.",
    )
    parser.addoption(
        "--live-db",
        action="store_true",
        default=False,
        help="Run tests marked live_db (off by default to protect live DBs).",
    )
    parser.addoption(
        "--run-integration",
        action="store_true",
        default=False,
        help="Run tests marked integration (Phase 4 smoke; off by default).",
    )


def pytest_collection_modifyitems(config, items) -> None:  # type: ignore[no-untyped-def]
    """Skip ``live_db`` tests unless ``--live-db`` was passed.

    Also skip ``integration`` tests unless ``--run-integration`` or
    ``pytest -m integration`` was explicitly passed.
    """
    import pytest

    if not config.getoption("--live-db"):
        skip_live = pytest.mark.skip(
            reason="needs --live-db; this test touches a live DB"
        )
        for item in items:
            if "live_db" in item.keywords:
                item.add_marker(skip_live)

    # If -m integration or --run-integration is set, run them; otherwise skip.
    markexpr = str(getattr(config.option, "markexpr", "") or "")
    run_integration = (
        config.getoption("--run-integration") or "integration" in markexpr
    )
    if not run_integration:
        skip_int = pytest.mark.skip(
            reason="integration test -- run via `make integration` or -m integration"
        )
        for item in items:
            if "integration" in item.keywords:
                item.add_marker(skip_int)


# ------------------------------------------------------------------ collect


def _collect_markers(items) -> dict[str, list[str]]:  # type: ignore[no-untyped-def]
    """Return ``{requirement_id: [test_nodeid, …]}`` from collected items."""
    mapping: dict[str, list[str]] = defaultdict(list)
    for item in items:
        for marker in item.iter_markers(name="requirement"):
            if not marker.args:
                continue
            rid = str(marker.args[0])
            mapping[rid].append(item.nodeid)
    return mapping


def _load_reqs() -> dict[str, dict[str, Any]]:
    """Return ``{requirement_id: {desc, status, phase, category}}``."""
    if not REQS_JSON.exists():
        return {}
    data = json.loads(REQS_JSON.read_text(encoding="utf-8"))
    out: dict[str, dict[str, Any]] = {}
    for bucket_name in ("v1", "v2"):
        bucket = data.get(bucket_name, {})
        for code, cat in bucket.items():
            for req in cat.get("requirements", []):
                out[req["id"]] = {
                    "desc": req.get("desc", ""),
                    "status": req.get("status", "pending"),
                    "phase": req.get("phase"),
                    "category": f"{bucket_name}/{code}",
                }
    return out


# ------------------------------------------------------------------ emit


def _build_matrix(
    reqs: dict[str, dict[str, Any]],
    covered: dict[str, list[str]],
) -> str:
    """Render the markdown matrix as a string."""
    all_marker_ids = set(covered.keys())
    req_ids = set(reqs.keys())
    orphan_markers = sorted(all_marker_ids - req_ids)
    orphan_reqs = sorted(req_ids - all_marker_ids)
    covered_reqs = sorted(req_ids & all_marker_ids)

    lines: list[str] = []
    lines.append("# Coverage Matrix\n")
    lines.append("")
    lines.append(
        "_Auto-generated by `scripts/pytest_reqs_plugin.py` from "
        "`@pytest.mark.requirement(...)` markers × `reqs.json`._\n"
    )
    lines.append("")

    # Top-line totals.
    total = len(req_ids)
    covered_n = len(covered_reqs)
    pct = (100 * covered_n / total) if total else 0.0
    lines.append(f"**Totals:** {covered_n}/{total} requirements covered "
                 f"({pct:.1f}%). "
                 f"{len(orphan_reqs)} ⚠️ uncovered · {len(orphan_markers)} ❌ "
                 f"orphan markers.\n")
    lines.append("")

    # Main table.
    lines.append("| Requirement | Category | Status | Covered by | Desc |")
    lines.append("|---|---|---|---|---|")

    def _fmt_tests(tests: list[str]) -> str:
        if not tests:
            return ""
        # Keep output short; show node ids sanitized for pipe chars.
        shown = [t.replace("|", "\\|") for t in tests]
        return "<br>".join(shown)

    for rid in sorted(req_ids):
        meta = reqs[rid]
        tests = covered.get(rid, [])
        mark = "" if tests else "⚠️"
        lines.append(
            f"| {mark}`{rid}` | {meta['category']} | {meta['status']} | "
            f"{_fmt_tests(tests)} | {meta['desc']} |"
        )

    # Orphan markers (tests reference an unknown ID).
    if orphan_markers:
        lines.append("")
        lines.append("## ❌ Orphan markers (ID not in reqs.json)")
        lines.append("")
        lines.append("| Marker ID | Test |")
        lines.append("|---|---|")
        for rid in orphan_markers:
            for test in covered[rid]:
                lines.append(f"| `{rid}` | `{test}` |")

    return "\n".join(lines) + "\n"


def pytest_sessionfinish(session, exitstatus) -> None:  # type: ignore[no-untyped-def]
    config = session.config
    if config.getoption("--no-coverage-matrix"):
        return
    items = getattr(session, "items", None) or []
    if not items:
        return
    reqs = _load_reqs()
    covered = _collect_markers(items)
    matrix = _build_matrix(reqs, covered)
    OUTPUT.write_text(matrix, encoding="utf-8")


__all__ = ["pytest_addoption", "pytest_collection_modifyitems", "pytest_sessionfinish"]
