"""Render the rekordbox schema the red-team fixture library builds from.

Requirements:
    - [if] a webui reader selects a real rekordbox column [then] the fixture has it
    - [if] pyrekordbox's models change [then] the committed snapshot is regenerated

Acceptance tests (mapped to :mod:`tests.scripts.test_redteam_fixture_library`):
    - [if] the committed snapshot differs from this render [then] the fixture drifted
    - [if] a mapped fixture track 500s on the listing or rb-meta [then] a table or
      column is missing

``scripts.redteam_fixture_library`` cannot import pyrekordbox: the fleet runs
it through ``uv run --no-project`` with no project dependencies (Codex P1 on
PR #3706). So the schema is rendered here, committed beside the builder as
:data:`SCHEMA_PATH`, and a test pins the snapshot to this render.

Column names and types come from pyrekordbox's models, which match a real
decrypted ``master.plain.db`` column for column. Their constraints do not:
pyrekordbox marks every column NOT NULL, but real rekordbox leaves every
column nullable except the two timestamps, defaults the ``rb_*`` status
flags to 0, and declares no foreign keys. The render applies real rekordbox's
constraints, so a NULL ImagePath is as legal here as it is in a real library.

Regenerate: ``uv run python -m scripts.redteam_fixture_schema``
"""

from __future__ import annotations

from pathlib import Path

from pyrekordbox.db6 import tables
from sqlalchemy import Column, MetaData, Table, text
from sqlalchemy.dialects import sqlite
from sqlalchemy.schema import CreateTable

SCHEMA_PATH = Path(__file__).with_name("redteam_fixture_rekordbox_schema.sql")
REQUIRED_COLUMNS = frozenset({"created_at", "updated_at"})
ZERO_DEFAULT_COLUMNS = frozenset(
    {"rb_data_status", "rb_local_data_status", "rb_local_deleted", "rb_local_synced"}
)
_HEADER = (
    "-- GENERATED by `uv run python -m scripts.redteam_fixture_schema`. Do not edit.\n"
    "-- Rekordbox master.db schema for the red-team fixture library: column names\n"
    "-- and types from pyrekordbox, constraints as real rekordbox declares them.\n\n"
)


def _as_real_rekordbox_column(column: Column) -> Column:
    """Copy a pyrekordbox column with the constraints real rekordbox uses."""
    return Column(
        column.name,
        column.type,
        primary_key=column.primary_key,
        nullable=column.name not in REQUIRED_COLUMNS,
        server_default=text("0") if column.name in ZERO_DEFAULT_COLUMNS else None,
    )


def render_rekordbox_schema() -> str:
    """Every pyrekordbox table as SQLite DDL, sorted by name for a stable diff."""
    metadata = MetaData()
    statements = []
    for name in sorted(tables.Base.metadata.tables):
        model = tables.Base.metadata.tables[name]
        table = Table(name, metadata, *(_as_real_rekordbox_column(c) for c in model.columns))
        statements.append(str(CreateTable(table).compile(dialect=sqlite.dialect())).strip() + ";")
    return _HEADER + "\n\n".join(statements) + "\n"


def main() -> None:
    SCHEMA_PATH.write_text(render_rekordbox_schema())
    print(f"[OK] wrote {SCHEMA_PATH}")


if __name__ == "__main__":
    main()
