"""Read-only Spotify acquisition queue endpoints.

The imported playlist itself is resolved through the shared ``StateBackend``.
The Phase 9 ``pending_tracks`` auxiliary table is deliberately read directly
from the configured state database because it is not part of that protocol.
This module never creates or repairs auxiliary state: missing or malformed
persisted data is an explicit server error.
"""
from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Annotated, Literal

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, ConfigDict, HttpUrl, TypeAdapter, ValidationError, field_validator

from apps.shared.state import db as state_db
from apps.spotify.state_writer import SUGGESTED_SOURCE_KEYS

from ..backend import NotFoundError, StateBackend
from ..deps import get_read_state

router = APIRouter(prefix="/spotify", tags=["spotify"])

_HTTP_URL = TypeAdapter(HttpUrl)


class SuggestedSourcesOut(BaseModel):
    """The five persisted acquisition links generated by the importer."""

    model_config = ConfigDict(extra="forbid")

    beatport: str
    bandcamp: str
    qobuz: str
    apple_music: str
    discogs: str

    @field_validator("*", mode="before")
    @classmethod
    def require_string_http_url(cls, value: object) -> str:
        if not isinstance(value, str):
            raise ValueError("suggested source must be a string URL")
        _HTTP_URL.validate_python(value)
        return value


class PendingTrackOut(BaseModel):
    """One persisted, unmatched Spotify playlist entry."""

    pending_id: int
    playlist_id: str
    position: int
    spotify_uri: str
    isrc: str | None
    title: str
    artist: str
    album: str | None
    duration_ms: int | None
    suggested_sources: SuggestedSourcesOut
    status: Literal["pending"]
    added_at: str


def _not_found(playlist_id: str) -> HTTPException:
    return HTTPException(
        status_code=404,
        detail={
            "code": "SPOTIFY_PLAYLIST_NOT_FOUND",
            "message": f"Spotify playlist not found: {playlist_id}",
        },
    )


def _server_error(code: str, message: str) -> HTTPException:
    return HTTPException(status_code=500, detail={"code": code, "message": message})


def _read_pending_rows(state_db_path: Path, playlist_id: str) -> list[sqlite3.Row]:
    """Read persisted pending rows without creating tables or migrations."""
    try:
        conn = state_db.open_ro(state_db_path)
    except (FileNotFoundError, sqlite3.DatabaseError) as exc:
        raise _server_error("STATE_DB_UNAVAILABLE", str(exc)) from exc

    try:
        conn.row_factory = sqlite3.Row
        table_exists = conn.execute(
            "SELECT 1 FROM sqlite_master WHERE type = 'table' "
            "AND name = 'pending_tracks'"
        ).fetchone()
        if table_exists is None:
            raise _server_error(
                "PENDING_TRACKS_TABLE_MISSING",
                "state database has no pending_tracks table; import Spotify first",
            )
        return list(conn.execute(
            "SELECT pending_id, playlist_id, position, spotify_uri, isrc, "
            "title, artist, album, duration_ms, suggested_sources_json, status, "
            "added_at FROM pending_tracks "
            "WHERE playlist_id = ? AND status = 'pending' "
            "ORDER BY position, pending_id",
            (playlist_id,),
        ))
    except sqlite3.DatabaseError as exc:
        raise _server_error("PENDING_TRACKS_READ_FAILED", str(exc)) from exc
    finally:
        conn.close()


def _to_pending_track(row: sqlite3.Row) -> PendingTrackOut:
    """Validate a row without normalizing or generating persisted links."""
    try:
        suggested_sources = json.loads(row["suggested_sources_json"])
        if not isinstance(suggested_sources, dict):
            raise ValueError("suggested_sources_json must decode to an object")
        if set(suggested_sources) != set(SUGGESTED_SOURCE_KEYS):
            raise ValueError(
                "suggested_sources_json must contain exactly the canonical "
                f"keys {SUGGESTED_SOURCE_KEYS!r}"
            )
        return PendingTrackOut(
            pending_id=row["pending_id"],
            playlist_id=row["playlist_id"],
            position=row["position"],
            spotify_uri=row["spotify_uri"],
            isrc=row["isrc"],
            title=row["title"],
            artist=row["artist"],
            album=row["album"],
            duration_ms=row["duration_ms"],
            suggested_sources=SuggestedSourcesOut.model_validate(suggested_sources),
            status=row["status"],
            added_at=row["added_at"],
        )
    except (json.JSONDecodeError, TypeError, ValidationError, ValueError) as exc:
        raise _server_error("MALFORMED_PENDING_TRACK", str(exc)) from exc


@router.get("/playlists/{playlist_id}/pending-tracks", response_model=list[PendingTrackOut])
def get_pending_tracks(
    playlist_id: str,
    request: Request,
    backend: Annotated[StateBackend, Depends(get_read_state)],
) -> list[PendingTrackOut]:
    """Return persisted pending rows for one imported Spotify playlist."""
    try:
        playlist = backend.get_playlist(playlist_id)
    except NotFoundError as exc:
        raise _not_found(playlist_id) from exc
    if playlist.vendor != "spotify":
        raise _not_found(playlist_id)

    configured_path = getattr(request.app.state, "state_db_path", None)
    if configured_path is None:
        raise _server_error("STATE_DB_UNAVAILABLE", "state database path is not configured")
    rows = _read_pending_rows(Path(configured_path), playlist_id)
    return [_to_pending_track(row) for row in rows]


__all__ = ["PendingTrackOut", "SuggestedSourcesOut", "router"]
